### ISSUE TITLE
imporve README for getting started

### ISSUE THREAD

**Issue by sebgoa** [bitnami/cabin#66]
Currently the readme is very minimal and does not show all the steps and dependencies to be able to get going with the project.

We should document things better.

**Comment by vtuson** [comment]
I think it is a must to document the format of the dotenv file.

also I tried to build Cabin for android and it is basically not working. Firtsly I had to upgrade to 25 build tools, since some of the react-native components required it for the latest version

Then, I kept getting a crash based in (i think) multidex being disable:
09-06 12:13:10.658 14144-14144/com.skippbox.cabin I/MultiDex: VM has multidex support, MultiDex support library is disabled.

In general, it seems really hard to duplicate a working build environment for the project following the read me.

Crash is:

                                                                   --------- beginning of crash
09-06 12:13:10.670 14144-14144/com.skippbox.cabin E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.skippbox.cabin, PID: 14144
                                                                    java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzac; or its super classes (declaration of 'com.google.android.gms.common.internal.zzac' appears in /data/app/com.skippbox.cabin-1/split_lib_dependencies_apk.apk:classes17.dex)
                                                                        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                                        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)

**Comment by kemcake** [comment]
@vtuson Most of the android build issues should be fixed with #67 , I started the project from scratch to see pain points, make sure to follow the steps on the [React Native Get started guide](http://facebook.github.io/react-native/releases/0.48/docs/getting-started.html) (I added a link in the readme, can't really copy every information...)

**Comment by vtuson** [comment]
Thanks, I have tried the pr and it builds fine, but it is not running for me.
